DEFAULT_INPUT_KEY = 'input'
DEFAULT_RESPONSE_KEYWORD_CODE = 'code'
DEFAULT_RESPONSE_KEYWORD_RESULT = 'result'
DEFAULT_RESPONSE_KEYWORD_ERROR = 'error'
TOKEN_TIMEOUT_TIME = 60 * 60 * 3  # 3 hours
PASSWORD_RECOVERY_TOKEN_TIMEOUT_TIME = 60 * 10  # 10 minutes
EMAIL_VALIDATION_TOKEN_TIMEOUT_TIME = 60 * 60 * 24  # 1 day